blank_issues_enabled: true
contact_links:
    - name: Questions and Help
      url: https://github.com/janestreet/magic-trace/discussions
      about: This issue tracker is not for support questions. Please refer to magic-trace's discussion forums.
